- name: Common | Get spoch time from local system
  shell: date +%s
  register: current_build_time_epoch
  run_once: true

- name: Common | Creates ssh dir
  file: path=/home/{{ ansible_env.USER }}/.ssh state=directory

- name: Common | Copy private key from local
  copy:
    src: ~/.ssh/id_rsa
    dest: /home/{{ ansible_env.USER }}/.ssh/id_rsa
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0600

- name: Common | Copy private Github creds from local
  copy:
    src: ~/.netrc
    dest: /home/{{ ansible_env.USER }}/.netrc
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Common | Copy .mbedcloud.json creds from local
  copy:
    src: ~/.mbedcloud.json
    dest: /home/{{ ansible_env.USER }}/.mbedcloud.json
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

# jq is needed to edit JSON structs from the command line
# moreutils contains sponge which can do inplace edits
- name: Common | Install packages with apt
  apt: name={{item}} state=installed
  with_items:
       - python-pip
       - libssl-dev
       - vim
       - most
       - tree
       - git
       - curl
       - wget
       - unzip
       - jq
       - moreutils
  become: yes
  become_method: sudo

- name: Common | Add github to our known_hosts
  shell: ssh-keyscan -H github.com > .ssh/known_hosts

- name: Common | Get mbedcloud api token
  shell: jq '.MBED_CLOUD_API_KEY' ~/.mbedcloud.json
  register: mbed_cloud_api_key
  run_once: true

- name: Common | Get mbedcloud api endpoint
  shell: jq '.MBED_CLOUD_API_ENDPOINT' ~/.mbedcloud.json
  register: mbed_cloud_api_endpoint
  run_once: true
