---
# tasks file for common
- name: Common | Creates ssh dir
  file: path=/home/{{ ansible_env.USER }}/.ssh state=directory

- name: Common | Copy private key from local
  copy:
    src: ~/.ssh/id_rsa
    dest: /home/{{ ansible_env.USER }}/.ssh/id_rsa
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0600

- name: Common | Copy private Github creds from local
  copy:
    src: ~/.netrc
    dest: /home/{{ ansible_env.USER }}/.netrc
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Common | Copy mbedcloud creds from local
  copy:
    src: ~/.mbedcloud
    dest: /home/{{ ansible_env.USER }}/.mbedcloud
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

# jq is needed to edit JSON structs from the command line
# moreutils contains sponge which can do inplace edits
- name: Common | Install common utilities with apt
  apt: state=latest pkg=vim,most,tree,git,curl,wget,unzip,jq,moreutils
  become: yes
  become_method: sudo

- name: Common | Add github to our known_hosts
  shell: ssh-keyscan -H github.com > .ssh/known_hosts
