---
# tasks file for common
- name: Common | Creates ssh dir
  file: path=/home/{{ generic_ubuntu_user }}/.ssh state=directory

- name: Common | Save private key from local user
  copy:
    src: ~/.ssh/id_rsa
    dest: /home/{{ generic_ubuntu_user }}/.ssh/id_rsa
    owner: "{{ generic_ubuntu_user }}"
    group: "{{ generic_ubuntu_user }}"
    mode: 0600

- name: Common | Save private Github creds
  copy:
    src: ~/.netrc
    dest: /home/{{ generic_ubuntu_user }}/.netrc
    owner: "{{ generic_ubuntu_user }}"
    group: "{{ generic_ubuntu_user }}"
    mode: 0400

- name: Common | Save mbedcloud creds
  copy:
    src: ~/.mbedcloud
    dest: /home/{{ generic_ubuntu_user }}/.mbedcloud
    owner: "{{ generic_ubuntu_user }}"
    group: "{{ generic_ubuntu_user }}"
    mode: 0400

- name: Common | Install common utilities with apt
  apt: state=latest pkg=vim,most,tree,git,curl,wget,unzip
  become: yes
  become_method: sudo

- name: Common | add github to our known_hosts
  shell: ssh-keyscan -H github.com > .ssh/known_hosts
