- name: mbed Dev | Clone the mbed manifest tool
  git:
    version: 'master'
    accept_hostkey: yes
    force: yes
    repo: https://github.com/ARMmbed/manifest-tool-restricted.git
    dest: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool-restricted"
    update: no

- name: mbed Dev | Install the mbed manifest tool with python-pip
  shell: pip install .
  args:
    chdir: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool-restricted"
  become: yes
  become_method: sudo

- name: mbed Cloud JavaScript App | Install NPM libs needed
  npm: name={{ item }} state=present global=yes
  with_items:
    - express-generator
  become: yes
  become_method: sudo

- name: mbed Cloud JavaScript App | Get the mbed Cloud JS quickstart
  git:
    version: 'firmware-updates'
    accept_hostkey: yes
    force: yes
    repo: 'https://github.com/ARMmbed/mbed-cloud-sdk-javascript-quickstart'
    dest: mbed-cloud-sdk-javascript-quickstart
    update: no
  become_user: "{{ ansible_env.USER }}"

- name: mbed Cloud JavaScript App | Create dotfile with mbed cloud creds
  template: dest="mbed-cloud-sdk-javascript-quickstart/.env" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}" mode=0600 src=envdotfile.j2

- name: mbed Cloud JavaScript App | Install NPM dependencies
  npm:
    path: mbed-cloud-sdk-javascript-quickstart
    state: latest
#  become_user: "{{ ansible_env.USER }}"

- name: mbed Cloud JavaScript App | Change the endpoint to 1.2 by patching NodeJS SDK
  replace:
    dest: mbed-cloud-sdk-javascript-quickstart/node_modules/mbed-cloud-sdk/lib/common/apiBase.js
    regexp: 'http:\/\/api.mbedcloud.com'
    replace: "{{ mbed_cloud_api_endpoint }}"
    backup: no

- name: mbed Cloud JavaScript App | Update the tty on the server app
  replace:
    dest: mbed-cloud-sdk-javascript-quickstart/app.js
    regexp: '/dev/tty'
    replace: '/dev/pts/0'
    backup: no
    
- name: mbed Cloud JavaScript App | copy rc.local startup script
  template: dest="/etc/rc.local" owner=root group=root mode=0755 src=rc.local.j2
  become: yes
  become_method: sudo

- name: mbed Cloud JavaScript App | bounce rc.local service to run our app
  systemd: state=restarted name=rc.local enabled=yes
  become: yes
  become_method: sudo
