- name: mbed Cloud JavaScript App | Get the mbed Cloud JS quickstart
  git:
    version: 'master'
    accept_hostkey: yes
    force: yes
    repo: 'https://github.com/ARMmbed/mbed-cloud-sdk-javascript-quickstart'
    dest: mbed-cloud-sdk-javascript-quickstart
    update: no
  become_user: "{{ ansible_env.USER }}"

- name: mbed Cloud JavaScript App | Install NPM dependencies
  npm:
    path: mbed-cloud-sdk-javascript-quickstart
    state: latest
    
- name: mbed Cloud JavaScript App | copy rc.local startup script
  template: dest="/etc/rc.local" owner=root group=root mode=0755 src=rc.local.j2
  become: yes
  become_method: sudo

- name: mbed Cloud JavaScript App | bounce rc.local service to run our app
  systemd: state=restarted name=rc.local enabled=yes
  become: yes
  become_method: sudo
