- name: get the mbed cloud javascript quickstart
  git:
    version: 'master'
    accept_hostkey: yes
    force: yes
    repo: 'https://github.com/ARMmbed/mbed-cloud-sdk-javascript-quickstart'
    dest: mbed-cloud-sdk-javascript-quickstart
    update: no
  become_user: "{{ ansible_env.USER }}"

- name: install npm dependencies
  npm:
    path: mbed-cloud-sdk-javascript-quickstart
    state: latest

- name: copy systemd script
  template: dest="/etc/systemd/system/nodeserver.service" owner=root group=root mode=0755 src=nodeserver.service.j2
  become: yes
  become_method: sudo

- name: bounce service to run our app
  systemd: state=restarted name=nodeserver enabled=yes
  become: yes
  become_method: sudo
