---
# tasks file for mbed-dev
- name: mbed Dev | Install Mercurial
  apt: state=latest pkg=mercurial
  become: yes
  become_method: sudo

- name: mbed Dev | Install GCC Cortex-A/R/M cross compiler
  apt: state=latest pkg=gcc-arm-none-eabi
  become: yes
  become_method: sudo

- name: mbed Dev | Install the ARM mbed CLI
  pip: name=mbed-cli
  become: yes
  become_method: sudo

- name: mbed Dev | Creates a {{ mbed_source_dir }} directory for firmware
  file: path={{ mbed_source_dir }} state=directory

# This repo already changed mbed-os.lib to point to version 5.5
- name: mbed Dev | Clone quickstart client to build our mbed-os application
  git:
    version: 'qs-base'
    accept_hostkey: yes
    force: yes
    repo: "{{ mbed_repo_url }}"
    dest: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"
    update: no

- name: mbed Dev | Update mbed client repo with library dependencies
  shell: /usr/local/bin/mbed update
  args:
    chdir: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"

- name: mbed Dev | Remove old PAL
  file:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/mbed-cloud-client/mbed-client-pal"
    state: absent    

- name: mbed Dev | Clone correct PAL
  git:
    version: 'ccbffd39ac2634444ec3cbadb7d99e66939044b1'
    accept_hostkey: yes
    force: yes
    repo: git@github.com:ARMmbed/mbed-client-pal.git
    dest: "{{ mbed_source_dir }}{{ mbed_repo_name }}/mbed-cloud-client/mbed-client-pal"
    update: no

# This is only needed because we updated the PAL
- name: mbed Dev | Sync mbed client repo with library dependencies
  shell: /usr/local/bin/mbed sync
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# This is only needed because we updated the PAL
- name: mbed Dev | Deploy mbed client repo with library dependencies
  shell: /usr/local/bin/mbed deploy
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy ~/.../mbed_cloud_dev_credentials.c from host
  copy:
    src: ~/Downloads/testing/mbedcloud/1.2/production/mbed_cloud_dev_credentials.c
    dest: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0664

- name: mbed Dev | Copy update_default_resources.c from manifest dir
  shell: cp /home/{{ ansible_env.USER }}/Downloads/manifest-tool/update_default_resources.c {{ mbed_source_dir }}{{ mbed_repo_name }}

- name: mbed Dev | Change LED blink color to RED in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_RED);'
    state: present

# Note: you need mbed-os 5.5 in order for this to work
# https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/bootloader/
- name: mbed Dev | Add mbed_app_start offset to mbed_app.json
  shell: jq '.target_overrides.K64F."target.mbed_app_start" = "0x20400"' mbed_app.json | sponge mbed_app.json
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Disable mbed-trace.enable in mbed_app.json
  shell: jq '.target_overrides."*"."mbed-trace.enable" = 0' mbed_app.json | sponge mbed_app.json
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# This is only needed because we updated the PAL
- name: mbed Dev | Update mbed client repo with library dependencies
  shell: /usr/local/bin/mbed update
  args:
    chdir: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"

- name: mbed Dev | Compile RED mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# You will end up with a combined bootload + firmware_app binary for the K64F
# that will be copied to /vagrant/FRDM-K64F-RED.bin
# -s 0 sets the initial time to Unix epoch 1/1/1970 00:00.00
- name: mbed Dev | Combine the bootloader and app to RED.bin
  shell: python combine_bootloader_with_app.py -s 0 --header-offset 0x20000 --app-offset 0x20400 -b mbed-bootloader-k64f.bin -a ../BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin -o /vagrant/FRDM-K64F-RED-{{ current_build_time_epoch.stdout }}.bin
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}/tools"

- name: mbed Dev | Change LED blink color to GREEN in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_GREEN);'
    state: present

- name: mbed Dev | Compile GREEN mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy green.bin to /vagrant
  shell: cp {{ mbed_source_dir }}{{ mbed_repo_name }}/BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin /vagrant/FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.bin

- name: mbed Dev | Change LED blink color to BLUE in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_BLUE);'
    state: present

- name: mbed Dev | Compile BLUE mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy blue.bin to /vagrant
  shell: cp {{ mbed_source_dir }}{{ mbed_repo_name }}/BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin /vagrant/FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.bin
