---
# tasks file for mbed-dev
- name: mbed Dev | Install Mercurial
  apt: state=latest pkg=mercurial
  become: yes
  become_method: sudo

- name: mbed Dev | Install GCC Cortex-A/R/M cross compiler
  apt: state=latest pkg=gcc-arm-none-eabi
  become: yes
  become_method: sudo

- name: mbed Dev | Install the ARM mbed CLI
  pip: name=mbed-cli
  become: yes
  become_method: sudo

- name: mbed Dev | Clone the mbed manifest tool
  git:
    version: 'master'
    accept_hostkey: yes
    force: yes
    repo: https://github.com/ARMmbed/manifest-tool-restricted.git
    dest: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool-restricted"
    update: no

- name: mbed Dev | Install the mbed manifest tool with PIP
  shell: pip install .
  args:
    chdir: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool-restricted"
  become: yes
  become_method: sudo

- name: mbed Dev | Creates a manifest tool directory
  file: path=/home/{{ ansible_env.USER }}/Downloads/manifest-tool state=directory

- name: mbed Dev | Initialize the manifest tool
  shell: manifest-tool init -d "mbed-quickstart-company" -m "FRDM-K64F" -q --force
  args:
    chdir: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool"

- debug: msg="the current date is {{ current_build_time_epoch }}"
- debug: msg="your mbed cloud api key is {{ mbed_cloud_api_key.stdout.strip('""') }}"
- debug: msg="your mbed cloud api endpoint is {{ mbed_cloud_api_endpoint.stdout.strip('""') }}"

- name: mbed Dev | Dump manifest data to /vagrant/FRDM-K64F-QS-MANIFEST-DATA-{{ current_build_time_epoch.stdout }}.json
  shell: jq '. | {"json":.}' .manifest_tool.json | jq ".\"pem\"=\"$(cat .update-certificates/default.key.pem)\"" | jq ".\"der\"=\"$(base64 -w0 .update-certificates/default.der)\"" | sponge "/vagrant/FRDM-K64F-QS-MANIFEST-DATA-{{ current_build_time_epoch.stdout }}.json"
  args:
    chdir: "/home/{{ ansible_env.USER }}/Downloads/manifest-tool"

- name: mbed Dev | Creates a {{ mbed_source_dir }} directory for firmware
  file: path={{ mbed_source_dir }} state=directory

# This repo already changed mbed-os.lib to point to version 5.5
- name: mbed Dev | Clone quickstart client to build our mbed-os application
  git:
    version: 'qs-base'
    accept_hostkey: yes
    force: yes
    repo: "{{ mbed_repo_url }}"
    dest: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"
    update: no

- name: mbed Dev | Update mbed client repo with library dependencies
  shell: /usr/local/bin/mbed update
  args:
    chdir: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"

- name: mbed Dev | Remove old PAL
  file:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/mbed-cloud-client/mbed-client-pal"
    state: absent    

- name: mbed Dev | Clone correct PAL
  git:
    version: 'ccbffd39ac2634444ec3cbadb7d99e66939044b1'
    accept_hostkey: yes
    force: yes
    repo: git@github.com:ARMmbed/mbed-client-pal.git
    dest: "{{ mbed_source_dir }}{{ mbed_repo_name }}/mbed-cloud-client/mbed-client-pal"
    update: no

# This is only needed because we updated the PAL
- name: mbed Dev | Sync mbed client repo with library dependencies
  shell: /usr/local/bin/mbed sync
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# This is only needed because we updated the PAL
- name: mbed Dev | Deploy mbed client repo with library dependencies
  shell: /usr/local/bin/mbed deploy
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy ~/.../mbed_cloud_dev_credentials.c from host
  copy:
    src: ~/Downloads/testing/mbedcloud/1.2/production/mbed_cloud_dev_credentials.c
    dest: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0664

- name: mbed Dev | Copy update_default_resources.c from manifest dir
  shell: cp /home/{{ ansible_env.USER }}/Downloads/manifest-tool/update_default_resources.c {{ mbed_source_dir }}{{ mbed_repo_name }}

- name: mbed Dev | Change LED blink color to RED in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_RED);'
    state: present

# Note: you need mbed-os 5.5 in order for this to work
# https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/bootloader/
- name: mbed Dev | Add mbed_app_start offset to mbed_app.json
  shell: jq '.target_overrides.K64F."target.mbed_app_start" = "0x20400"' mbed_app.json | sponge mbed_app.json
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Disable mbed-trace.enable in mbed_app.json
  shell: jq '.target_overrides."*"."mbed-trace.enable" = 0' mbed_app.json | sponge mbed_app.json
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# This is only needed because we updated the PAL
- name: mbed Dev | Update mbed client repo with library dependencies
  shell: /usr/local/bin/mbed update
  args:
    chdir: "{{ mbed_source_dir }}/{{ mbed_repo_name }}"

- name: mbed Dev | Compile RED mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

# You will end up with a combined bootload + firmware_app binary for the K64F
# that will be copied to /vagrant/FRDM-K64F-RED.bin
# -s 0 sets the initial time to Unix epoch 1/1/1970 00:00.00
- name: mbed Dev | Combine the bootloader and app to RED.bin
  shell: python combine_bootloader_with_app.py -s 0 --header-offset 0x20000 --app-offset 0x20400 -b mbed-bootloader-k64f.bin -a ../BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin -o /vagrant/FRDM-K64F-RED-{{ current_build_time_epoch.stdout }}.bin
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}/tools"

- name: mbed Dev | Change LED blink color to GREEN in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_GREEN);'
    state: present

- name: mbed Dev | Compile GREEN mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy green.bin to /vagrant
  shell: cp {{ mbed_source_dir }}{{ mbed_repo_name }}/BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin /vagrant/FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.bin

- name: mbed Dev | Change LED blink color to BLUE in binary
  lineinfile:
    path: "{{ mbed_source_dir }}{{ mbed_repo_name }}/main.cpp"
    regexp: 'DigitalOut[ ]*led\((LED_RED|LED_GREEN|LED_BLUE)\);'
    line: 'DigitalOut led(LED_BLUE);'
    state: present

- name: mbed Dev | Compile BLUE mbed client FRDM-K64F
  shell: /usr/local/bin/mbed compile -m K64F -t GCC_ARM >> mbed-cli-compile.log
  args:
    chdir: "{{ mbed_source_dir }}{{ mbed_repo_name }}"

- name: mbed Dev | Copy blue.bin to /vagrant
  shell: cp {{ mbed_source_dir }}{{ mbed_repo_name }}/BUILD/K64F/GCC_ARM/mbed-cloud-client-example-sources-internal.bin /vagrant/FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.bin

# Upload blue.bin with cURL and save resource path to blue.json and save image location and ID


# - name: Dump base64 binary
#   slurp:
#     src: FRDM-K64F-GREEN-1497573263.bin
#   register: file_payload

# - debug:
#     msg: "{{ file_payload['content'] | b64decode -w0 }}"

# - name: mbed Dev | POST mbedcloud/v3/firmware-images upload firmware
#   uri:
#     url: https://api.us-east-1.mbedcloud.com/v3/firmware-images/
#     method: POST
#     body: "datafile={{ lookup('file', FRDM-K64F-GREEN-1497573263.bin) }}&name=FRDM-K64F-GREEN-1497573263.bin"
#     headers:
#       authorization: "Bearer {{ mbed_cloud_api_key.stdout.strip('""') }}"
#       content-type: multipart/form-data
#     status_code: 201
#     body_format: raw
#     return_content: yes

########## GREEN
# - name: mbed Dev | POST mbedcloud/v3/firmware-images upload firmware
#   shell: curl -s -X POST https://api.us-east-1.mbedcloud.com/v3/firmware-images/ -H 'authorization:Bearer "{{ mbed_cloud_api_key.stdout.strip('""') }}.stdout"' -H 'content-type:multipart/form-data' -F datafile=@/vagrant/FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.bin -F name=FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.bin > post-image-response-{{ current_build_time_epoch.stdout }}.json
#   args:
#     chdir: /home/{{ ansible_env.USER }}/Downloads

# - name: mbed Dev | Create a manifest by pulling out the datafile from the results.json
#   shell: manifest-tool create -u $(jq '.datafile' /vagrant/post-image.json) -p /vagrant/FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout.strip('""') }}.bin -o FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.manifest
#   args:
#     chdir: /home/{{ ansible_env.USER }}/Downloads/

# - name: mbed Dev | Upload green manifest with cURL to mbed Cloud and save manifest resource ID
#   shell: curl -s -X POST https://api.us-east-1.mbedcloud.com/v3/firmware-manifests/ -H 'authorization: Bearer {{ mbed_cloud_api_key.stdout.strip('""') }}' -H 'content-type: multipart/form-data' -F datafile=@FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.manifest -F name=FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.manifest > post-manifest-{{ current_build_time_epoch.stdout }}.json
#   args:
#     chdir: /home/{{ ansible_env.USER }}/Downloads

# curl -s -X POST https://api.us-east-1.mbedcloud.com/v3/firmware-manifests/ -H 'authorization: Bearer {{ mbed_cloud_api_key.stdout.strip('""') }}' -H 'content-type: multipart/form-data' -F datafile=@FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.manifest -F name=FRDM-K64F-GREEN-{{ current_build_time_epoch.stdout }}.manifest > post-manifest-{{ current_build_time_epoch.stdout }}.json

# Create blue filter with cURL to mbed Cloud based on custom_attributes

# curl -s -X POST https://api.us-east-1.mbedcloud.com/v3/device-queries/ -H 'authorization: Bearer {{ mbed_cloud_api_key.stdout.strip('""') }}' -H 'content-type: application/json' -d '{"name": "my_filter_name","query": "description=my_filter_description&id=015cac1279560000000000010010036d"}' > post-filter-{{ current_build_time_epoch.stdout }}.json

# Create blue campaign with cURL to mbed Cloud with image ID

# curl -X POST https://api.us-east-1.mbedcloud.com/v3/update-campaigns/ -H 'authorization: Bearer {{ mbed_cloud_api_key.stdout.strip('""') }}' -H 'content-type: application/json' -d '{"name": "my update campaign name","device_filter": "name=my_filter_name","description": "my update campaign description","state": "draft","root_manifest_id": "015caea4b2e10000000000010010015d","root_manifest_url": "http://firmware-catalog-media-ca57.s3.amazonaws.com/manifest.file"}' > post-campaign-{{ current_build_time_epoch.stdout }}.json

# Add custom_attributes to devices connected


########## BLUE

# - name: mbed Dev | POST mbedcloud/v3/firmware-images upload firmware
#   shell: curl -s -X POST https://api.us-east-1.mbedcloud.com/v3/firmware-images/ -H 'authorization:Bearer "{{ mbed_cloud_api_key.stdout.strip('""') }}"' -H 'content-type:multipart/form-data' -F datafile=@/vagrant/FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.bin -F name=FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.bin > post-image-response-{{ current_build_time_epoch.stdout }}.json
#   args:
#     chdir: /home/{{ ansible_env.USER }}/Downloads

# - name: mbed Dev | Create a manifest by pulling out the datafile from the results.json
#   shell: manifest-tool create -u $(jq '.datafile' /vagrant/post-image.json) -p /vagrant/FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.bin -o FRDM-K64F-BLUE-{{ current_build_time_epoch.stdout }}.manifest
#   args:
#     chdir: /home/{{ ansible_env.USER }}/Downloads
